import { useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import { Archive as ArchiveIcon, FolderTree, Package, RotateCcw, Search, Trash2 } from "lucide-react";
import Layout from "../components/Layout";
import { apiRequest } from "../services/api";

export default function Archive(){
  const [tab,setTab]=useState("categories"),[categories,setCategories]=useState([]),[products,setProducts]=useState([]),[search,setSearch]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState("");
  const load=async()=>{const [c,p]=await Promise.all([apiRequest("/api/categories?status=archived"),apiRequest("/api/products?status=archived&limit=100")]);setCategories(c.data||[]);setProducts(p.data||[])};
  useEffect(()=>{load().catch(e=>setError(e.message))},[]);
  const items=tab==="categories"?categories:products;
  const filtered=useMemo(()=>items.filter(x=>`${x.name?.en||""} ${x.name?.ar||""} ${x.slug||""}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
  const action=async(item,type)=>{if(type==="permanent"&&!confirm(`Delete “${item.name?.en||"this item"}” permanently?${tab==="categories"?" Its products will also be deleted.":""}`))return;setBusy(item._id);setError("");try{await apiRequest(`/api/${tab}/${item._id}/${type==="restore"?"restore":"permanent"}`,{method:type==="restore"?"PATCH":"DELETE"});await load()}catch(e){setError(e.message)}finally{setBusy("")}};
  return <Layout title="Archive"><motion.section initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="relative mb-7 overflow-hidden rounded-[2rem] bg-black p-8 text-white shadow-xl"><div className="absolute -right-10 -top-16 h-52 w-52 rounded-full bg-red-600/30 blur-3xl"/><div className="relative flex items-center gap-4"><span className="rounded-2xl bg-red-600 p-3 shadow-lg"><ArchiveIcon/></span><div><p className="text-xs font-black uppercase tracking-[.3em] text-red-500">Content safety</p><h1 className="mt-1 text-3xl font-black">Archive</h1><p className="mt-1 text-sm text-neutral-400">Restore removed content or permanently clean it up.</p></div></div></motion.section>
  <div className="mb-6 flex flex-col justify-between gap-4 md:flex-row"><div className="inline-flex self-start rounded-2xl bg-white p-1.5 shadow-sm ring-1 ring-black/5"><Tab active={tab==="categories"} onClick={()=>setTab("categories")} icon={<FolderTree size={17}/>} label="Categories" count={categories.length}/><Tab active={tab==="products"} onClick={()=>setTab("products")} icon={<Package size={17}/>} label="Products" count={products.length}/></div><div className="flex items-center gap-3 rounded-2xl bg-white px-4 py-3 shadow-sm ring-1 ring-black/5 md:w-80"><Search size={18} className="text-neutral-400"/><input className="w-full bg-transparent outline-none" placeholder="Search archive..." value={search} onChange={e=>setSearch(e.target.value)}/></div></div>
  {error&&<p className="mb-5 rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}
  {!filtered.length?<div className="rounded-3xl bg-white p-16 text-center shadow-sm ring-1 ring-black/5"><ArchiveIcon className="mx-auto text-neutral-300" size={44}/><h2 className="mt-4 text-xl font-black">Nothing archived</h2><p className="mt-1 text-neutral-500">Removed {tab} will appear here.</p></div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((item,index)=><motion.article key={item._id} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:index*.035}} className="overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-black/5"><div className="flex gap-4 p-5">{image(item)?<img src={image(item)} className="h-20 w-20 rounded-2xl bg-neutral-100 object-contain"/>:<span className="flex h-20 w-20 items-center justify-center rounded-2xl bg-neutral-100"><Package/></span>}<div className="min-w-0"><span className="rounded-full bg-red-50 px-2.5 py-1 text-[10px] font-black uppercase text-red-600">{tab==="categories"?item.section:item.category?.name?.en||"Product"}</span><h2 className="mt-3 truncate text-lg font-black">{item.name?.en}</h2><p dir="rtl" className="truncate text-sm text-neutral-500">{item.name?.ar}</p></div></div><div className="flex items-center justify-between border-t bg-neutral-50 px-5 py-4"><span className="text-xs text-neutral-400">{item.archivedAt?new Date(item.archivedAt).toLocaleDateString():"Archived"}</span><div className="flex gap-2"><button disabled={busy===item._id} onClick={()=>action(item,"restore")} className="flex items-center gap-2 rounded-xl bg-black px-3 py-2 text-xs font-black text-white hover:bg-red-600 disabled:opacity-40"><RotateCcw size={14}/>Restore</button><button disabled={busy===item._id} onClick={()=>action(item,"permanent")} className="rounded-xl border border-red-200 p-2 text-red-600 hover:bg-red-50 disabled:opacity-40"><Trash2 size={15}/></button></div></div></motion.article>)}</div>}</Layout>;
}
const image=x=>x.image?.url||x.images?.[0]?.url;
const Tab=({active,onClick,icon,label,count})=><button onClick={onClick} className={`flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-black transition ${active?"bg-black text-white":"text-neutral-500 hover:bg-neutral-100"}`}>{icon}{label}<span className={`rounded-full px-2 py-0.5 text-xs ${active?"bg-red-600 text-white":"bg-neutral-100"}`}>{count}</span></button>;
