import { useEffect, useState } from "react";
import { Pencil, Plus, ShieldCheck, Trash2, UserRound, X } from "lucide-react";
import Layout from "../components/Layout";
import { apiRequest } from "../services/api";

const options=[["dashboard","Dashboard"],["messages","Messages"],["build_requests","Build Requests"],["project_briefs","Production Briefs"],["categories","Categories"],["products","Products"],["shipments","Shipment Portfolio"],["archive","Archive"]];
const blank={name:"",email:"",password:"",role:"employee",permissions:["dashboard"],isActive:true};
export default function Users(){const [users,setUsers]=useState([]),[form,setForm]=useState(null),[error,setError]=useState("");const load=()=>apiRequest("/api/admin/users").then(r=>setUsers(r.data||[]));useEffect(()=>{load().catch(e=>setError(e.message))},[]);
const save=async e=>{e.preventDefault();setError("");try{const body={...form};delete body.id;delete body._id;if(!body.password)delete body.password;await apiRequest(form._id?`/api/admin/users/${form._id}`:"/api/admin/users",{method:form._id?"PATCH":"POST",body:JSON.stringify(body)});setForm(null);await load()}catch(e){setError(e.message)}};
const remove=async u=>{if(!confirm(`Delete ${u.name}'s account?`))return;try{await apiRequest(`/api/admin/users/${u.id||u._id}`,{method:"DELETE"});await load()}catch(e){setError(e.message)}};
return <Layout title="Team Access"><div className="mb-8 flex flex-col justify-between gap-5 rounded-[2rem] bg-black p-8 text-white shadow-xl md:flex-row md:items-center"><div><p className="text-xs font-black uppercase tracking-[.3em] text-red-500">Security & access</p><h1 className="mt-2 text-3xl font-black">Admins & Employees</h1><p className="mt-2 text-neutral-400">Give every employee access only to the sections they manage.</p></div><button onClick={()=>setForm(structuredClone(blank))} className="flex items-center justify-center gap-2 rounded-xl bg-red-600 px-5 py-3 font-black"><Plus/>Add employee</button></div>{error&&<p className="mb-5 rounded-2xl bg-red-50 p-4 text-red-700">{error}</p>}<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{users.map(u=><article key={u.id||u._id} className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-black/5"><div className="flex items-start justify-between"><span className="rounded-2xl bg-neutral-100 p-3"><UserRound/></span><span className={`rounded-full px-3 py-1 text-xs font-black ${u.isActive?"bg-emerald-50 text-emerald-700":"bg-neutral-100 text-neutral-500"}`}>{u.isActive?"Active":"Disabled"}</span></div><h2 className="mt-5 text-xl font-black">{u.name}</h2><p className="text-sm text-neutral-500">{u.email}</p><div className="mt-4 flex flex-wrap gap-1.5">{u.role!=="employee"?<span className="rounded-full bg-red-50 px-3 py-1 text-xs font-bold text-red-600"><ShieldCheck className="mr-1 inline" size={13}/>{u.role==="super_admin"?"Owner":"Admin · Full access"}</span>:(u.permissions||[]).map(p=><span key={p} className="rounded-full bg-neutral-100 px-2.5 py-1 text-[11px] font-bold">{options.find(x=>x[0]===p)?.[1]||p}</span>)}</div><div className="mt-6 flex gap-2"><button onClick={()=>setForm({...u,_id:u.id||u._id,password:""})} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-black px-4 py-2.5 text-sm font-bold text-white"><Pencil size={15}/>Edit</button>{u.role!=="super_admin"&&<button onClick={()=>remove(u)} className="rounded-xl border border-red-200 p-2.5 text-red-600"><Trash2 size={17}/></button>}</div></article>)}</div>{form&&<Modal form={form} setForm={setForm} save={save}/>}</Layout>}
function Modal({form,setForm,save}){const toggle=p=>setForm({...form,permissions:form.permissions?.includes(p)?form.permissions.filter(x=>x!==p):[...(form.permissions||[]),p]});return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-5"><form onSubmit={save} className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-7"><div className="flex items-center justify-between"><h2 className="text-2xl font-black">{form._id?"Edit account":"Add employee"}</h2><button type="button" onClick={()=>setForm(null)}><X/></button></div><div className="mt-6 grid gap-4 md:grid-cols-2"><Field label="Name" value={form.name} onChange={v=>setForm({...form,name:v})}/><Field label="Email" type="email" value={form.email} onChange={v=>setForm({...form,email:v})}/><Field label={form._id?"New password (optional)":"Password"} type="password" required={!form._id} value={form.password} onChange={v=>setForm({...form,password:v})}/><label className="text-sm font-bold">Account type<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className="mt-2 w-full rounded-xl border p-3"><option value="employee">Employee · selected access</option><option value="admin">Admin · full access</option></select></label></div>{form.role==="employee"&&<div className="mt-6"><h3 className="font-black">Allowed sections</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{options.map(([key,label])=><label key={key} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 text-sm font-bold ${form.permissions?.includes(key)?"border-red-500 bg-red-50":""}`}><input type="checkbox" checked={form.permissions?.includes(key)} onChange={()=>toggle(key)}/>{label}</label>)}</div></div>}<label className="mt-5 flex items-center gap-3 font-bold"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/>Account active</label><button className="mt-6 w-full rounded-xl bg-red-600 p-3 font-black text-white">Save account</button></form></div>}
const Field=({label,value,onChange,type="text",required=true})=><label className="text-sm font-bold">{label}<input required={required} type={type} value={value||""} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border p-3 outline-none focus:border-red-500"/></label>;
